[package]
name = "warrant-render"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
warrant-core = { version = "0.1.0", path = "../core" }

[dev-dependencies]
pretty_assertions.workspace = true
