[package]
name = "warrant-authority"
version.workspace = true
edition.workspace = true
rust-version = "1.90"
license.workspace = true

[dependencies]
jiff.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_json_canonicalizer.workspace = true
sha2.workspace = true
warrant-core = { version = "0.1.0", path = "../core" }

[dev-dependencies]
pretty_assertions.workspace = true
tempfile.workspace = true
