[package]
name = "warrant-model"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
petgraph.workspace = true
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_json_canonicalizer.workspace = true
sha2.workspace = true
warrant-core = { version = "0.1.0", path = "../core" }

[dev-dependencies]
pretty_assertions.workspace = true
tempfile.workspace = true
