[package]
name = "warrant-lang-rust"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
cargo_metadata.workspace = true
serde.workspace = true
serde_json.workspace = true
warrant-core = { version = "0.1.0", path = "../core" }
warrant-model = { version = "0.1.0", path = "../model" }

[dev-dependencies]
pretty_assertions.workspace = true
tempfile.workspace = true
